GitHub Actions Initialized and Running
Dhirajk1/CS222-Group85 pull request #19
Opened 2022-10-14 23:59 UTC by kulksoh21

This was a high-priority fix that is now completed. This issue was preventing our mentor and others from checking whether or not the code actually runs or not. GitHub actions now work as can be seen in this pull request. I have a "dummy" test case in place in order to test this action and I have also set up the linter in actions. They both run successfully, so the mentor will easily verify the code next week.

2022-10-15 00:39 UTC, AryanMashruwala requested changes
Good on getting actions working. Remember not to have unrunnable code in future pull requests. We cannot have broken code in higher branches like last week. Also since tests are yet to be completed, we will have @Dhirajk1 complete them to ensure backend testing is sufficient.

2022-10-15 18:48 UTC, Dhirajk1 commented
Fixed test cases present in the `Calendar-Class` branch (along with some minor bug fixes and organization). *This will end up being the leading code for the backend as of merging*

2022-10-15 21:43 UTC, AryanMashruwala commented
When running this branch locally, there are a lot of pylint warnings. Make sure github actions run the linter correctly to fix this issue. Also, commented-out test cases cannot be merged into higher branches of the backend; those should not be in the final version of the code before moving on to the next stage.

2022-10-17 12:50 UTC, Dhirajk1 commented
All problems fixed by yours truly 🥰

2022-10-17 12:53 UTC, closed without merging